import json
from datetime import datetime, timezone

now = datetime.now(timezone.utc)

event = [
    {
        "title": "GitHub Intelligence Event",
        "text": "Automatic intelligence update generated by GitHub Collector.",
        "source": "GitHub Intelligence Collector",
        "severity": "info",
        "icon": "🛰️",
        "timestamp": now.isoformat(),
        "location": "Athens",
        "lat": 37.9838,
        "lon": 23.7275
    }
]

with open("data/live-intel.json", "w", encoding="utf-8") as f:
    json.dump(event, f, indent=2)

print("live-intel.json updated")
